language: python
python:
- '3.5.0'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database fast_food_fast;' -U postgres
- export FLASK_ENV=development
script:
- pytest -v --cov app --cov-report term-missing
after_success:
- coveralls