language: python
python:
- '3.5.0'
install:
  - pip install -r requirements.txt
env:
  - TESTING = True
services:
  - postgresql
before_script:
  - psql -c 'create database fast_food_fast;'  -U postgres
  - pip install coverage coveralls
  - pip install python-coveralls
  - pip install pytest pytest-cov
addons:
  postgresql: "9.5"
script:
  - pytest --cov=.
  - coverage  
  - coveralls 
  - python setup.py install
  
after_success:
- coveralls