language: python
python:
- "3.5.0"
# command to install dependencies
services:
- postgresql
install:
- pip install -r requirements.txt
- psql -c 'create database fast_food_fast;'  -U postgres
- pip install pytest
- pip install pytest-cov
- pip install coveralls
addons:
- postgresql: "9.5"
# command to run tests
script:
- pytest --cov=.
- coverage
- coveralls
after_success:
- coveralls