language: python
python:
- '3.5.0'

services:
  -postgresql

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - psql -c 'create database fast_food_fast;' -U postgres

# command to run tests
script:
   - pytest -v --cov app --cov-report term-missing


after_success:
  - coveralls